# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

# The version of the configuration file format.
version: "0.2"
# The locale to use when spell checking. (e.g., en, en-GB, de-DE
language: 'en,ru'
files:
  - "**/*.{js,ts}"
ignorePaths:
  - "src/app/file-upload/file-upload.service.ts"
  - "src/@generated/**"
dictionaries:
  - typescript
  - en
useGitignore: true
minWordLength: 4
maxNumberOfProblems: 100
cache:
  useCache: true

flagWords:
  - hte
  - teh
  - recieve

words:
  - liteend
  - pactum
  - unplugin
  - ofetch
  - psql
  - pgpassword
  - qljson
  - logto
  - Menlo
  - Consolas
